[package]
name = "tauri-plugin-vibrancy"
description = "Add vibancy/blur/acrylic effects to your tauri window."
authors = [ "Amr Bashir <amr.bashir2015@gmail.com>" ]
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
license = "MIT"
readme = "README.md"
repository = "https://github.com/amrbashir/tauri-plugin-vibrancy"
documentation = "https://docs.rs/tauri-plugin-vibrancy"
keywords = [ "vibrancy", "acrylic", "blur", "tauri", "gui", "plugin", "tauri-plugin" ]
categories = [ "gui" ]


[dependencies]
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next" }
tao = { git = "https://github.com/tauri-apps/tao", branch = "next" }
log = "0.4"

[target."cfg(target_os = \"windows\")".dependencies.windows]
  version = "0.28.0"
  features = [
  "alloc",
  "Win32_Foundation",
  "Win32_System_LibraryLoader",
  "Win32_System_SystemInformation",
  "Win32_Graphics_Gdi",
  "Win32_Graphics_Dwm",
  "Win32_UI_WindowsAndMessaging"
]

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.24"
objc = "0.2"
